name: Label All PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label-all-prs:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write  # Ensure this permission is set to allow labeling

    steps:
    - name: Add 'awesome' label to all PRs
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'awesome'
