name: Label All PRs

on:
  pull_request:
    types: [opened, edited, reopened]  # Trigger on various PR events

jobs:
  label_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only read access needed
      pull-requests: read  # Read access for PR info
      repository-projects: read  # Not required for this workflow (optional)

    steps:
      - uses: actions/checkout@v2
      - name: Add 'awesome' label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['awesome']
            });
