name: Label All PRs

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  label-all-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Add 'awesome' label to all PRs
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        labels: 'awesome'
